------New series of simple scripts that just work..nothing fancy                                                                                                                                                   
--                                                                                                                                                    
--                                                                                                                                                    
--                                       .                                                                                                            
--                                ,c6                                                                                                                 
--                             ;6BB  @                                                                                                                
--                          ,TBd;   ;T@                                                                                                               
--                         @B    :U8c .@                                                                                                              
--                         ::i#Ui      ;@                                                                                                             
--                         :; B         S@                                                                                                            
--                          E P:       6.,                                                                                                            
--                          8  ;   ,;rBSL                                                                                                             
--                           BcB b@ @,x @                                                                                                             
--                            OrB  H@@  UP                                                                                                            
--                            x F.   B   B                                                                                                            
--              ;0;:           @ d    B  @i                                                                                                           
--             U.B r@T          @ #   ds  @                                                                                                           
--           ZB r  F .bs         @,;   X  ;E                                                                                                          
--          Sn : ;j    .Dc        @P   r@B g                                                                                                          
--          B2 ;:        :B        @Z  @B2@ 8:                                                                                                        
--           @ B.       ;t@         @  BPbSBHB8                ,r;rrjrrr:7                                                                            
--           ;B S;    rx;  @        s@.  iBx  ,@sUr           rt8 ,,,,;;.t.                                                                           
--            r@ B;  BB;    @c      .B.SF  rr6.b: :g@          5 r        B                                                                           
--              .;BD2  nB    SB      @ sr B@P0B@;  n:Ob5       #;F        @                                                                           
--                 0@;   drsT ;B;   P@8 @ #g@B.  s@s;i s@2  7BF @ @       #B                                                                          
--                   @@  sB@B@: B@rD.  ,LD r    BUU;     7B@    r@;        @                                                                          
--                    @BL ##@  B: xBc         @B  .i       .8j   B2r ...   B                                                                          
--                     @:@,O BB.     @       @B    S@T       8B:  @CEZXS:6B@                                                                          
--                     ,@ # @B tn0@6#B     n@.      @          0@      s@2                                                                            
--      ;UB@OTB@B.      :B2@    B@BBB@    B@        B            @b  r0;                                                                              
--     B8:ELjB. @O         D@BS  @UBr    Br         .B             b@                                                                                 
--     d g   @  B@B@ssHrFrEs   ;r,c    sB            @ S             @;                                                                               
--    ii B  @j #@ Ld@ PBPr@B@Hr;      @B              @;           ,:@,                                                                               
--    E j   B  @    8L @ r7L:@B,5@BSO@                @            rB                                                                                 
--  .@8  . is nBLB@Bn @       @r   U@rB              :@B          @#                                                                                  
--   rB@ ;r58;BF 0B@ nB    .8@    Bs   @B            @ @,@      .@.                                                                                   
--     8@nr :B  ;2F @@ tbB@O B@ iB      2B.        ,@  ;@      E@                                                                                     
--        rHt:B@B  @.    @0@HC @B         B@      BC    B     BB                                                                                      
--               B@s ,.  B@Xx @;           j@;  P@      Cr   B,                                                         .                             
--                srU@@@.   ;@               rL@x        O.@Bx rr                    .rc.                                                             
--                     BL  gs                j@          ;@  r .,6@,                Ot.rO8;                                                           
--                      Br5r               ,@i          .@B D;.  ST:B      ;r,     Hi    rB                                                           
--                       Bs6              ZB           B@  @@. c@2  nB    Ht ;@   .@ 7s: Br                                                           
--                         5BZ           @r           B8 8   @  C    @    B@B  @gZB@B; B:@              ircS,                                         
--                           rBC;      r@           .B .@ bO  @  B;. BcjDX..B  t;    @ 8@   d          @7   ;i                                        
--                             @B@2   tE           sx @ ;@ #  B .@:: @ H    8C;@     b @   @:x O,    ;Bs     Ss;jB                                    
--                            ,n: rB@B            @B;.O@;BSBS:@#;   D .B    @  r;   7B BZ,@Z r@ @.  X5   ;@@X0Z   86:                                 
--                             c .  BDBU         @n j@  B ;8 : r ,S8; B    .F  n.   BP  ; .ccL   @ B.   L@  j  U T, r@                                
--                             n t  H xB@B     c@B  @ .B;n#O@ijB2U@  5@    .@js#    @  8S         @t., B@   L;;nn     @                               
--                             b 2  x;x j @L jB@@ r@   @ ;  @  @Ot   @     Zs .@    B; ;P@    HTi :2  Bd:    .B;  ULri @                              
--                             8 .; cT..U  B@O0  B@Z  @r B  @  Z@B  TB     P   ;    @ :B 5@  B; s8 B  g:i   S@   8    Z0                              
--                             ;isBir@ @ P  BD#E@F  ,@B Bc  B  @i@  B;r@B@U@LcBc;, gB, BB Bs  FcL   B HXx; Et    ,i  T;C                              
--                              @ U  B  @:;r ,rt, s2@  BP  @s  #PB 0@  .: i2  @ x5rB  @.@B B     rd 6B@   ;S;   . :xH @.                              
--                             .8 @  ij  OU;,         B  T@   .@.@  B     6  j5   .@ c @  @ B ,C;jr8.@#jr;   XX:;, :  B5                              
--                              @ @.  @ir   r@s:;iST#F  @B   sP cB  @     @j:B    @  FFB  ;B;Z.r@  j@O iL rO.i  .r@  B @8                             
--                              B Pr   rb@@i   , ;;   Xd ,B7r  @ @  L@;i X  .@   ;B .0B    ,F@88B. @  r  D: ;@g2B@  Z@  B .c,r;,                      
--                              rB  iL;    .:B@Lr   s@,   xB r@  B@i;B CxB  :@OFrB  @B  8@     B  Br  .Br si .str  sr8   BSS;; ,jT;.   ,;rrCr         
--                               #.,  :Cj;  #;  7x0Z;   En  Bt   XB  Z   @niB   BH TB,        B@ ZB ;   cB, r5.  SCxB@   @  @.rt  ;CtjBdd   H;       7
--                                 rOx;  iOB          rP   B,     @ rSd8@  P@ iB  UBs SB     B@  B ; O i  ;;CcO8U:;r  @r r@U  5@@     , @r ,;B     B@,
--                                    r2HgBF;,iCSc:  B5  @B        @F  B@@BC,@ @;EBO  .;    B@  B   B0X@BHLr,....      Tg BjB@  ;@  .j  Bt   @  : 2B  
--                                        ;HH.    ;t@  ;@i           @@@: rO ,6n@Bj  2  sB@B@ ;B  @TsCs        ; r5B6   iB   BB2 B;;r EB  ZrBB@;Cs@  ;
--                                           ;rXc;  tcZP             @ .B7r@ircFS:   8 ;@ t  @7.BnH;     ;ibB@BiB@csB@B. @    B   B  @ i   @F   .C@b r
--                                               .;rib              @    B  ,,          @B#B@B  @;    rb@8S,   ;7  xO, BE @   #r  @ HU :cB@    c@ . s 
--                                                                 8B   B           Br   , .  B@    r@BT;    BB0     @B r@8   Br 6Br Sr BL rCc iFrr;  
--                                                                ,@rBUr@            ,@    6nF@    B@c   U; @r  ;      B  @  #@  8 i: O5@    ,@B   :x;
--                                                                S  r6@#8d82@b6BHX@iOjnSBO;t@    b0.    : CB           B C;B@  @;  iD:  rO72;B :Z2;  
--                                                                @    n  r;r,,    ;i       @: i;BE         @           C8 B  ;;i LB,  ;c;Xg rO    ;#:
--                                                                B   rr           Ct      @H   r@r       ;. @ @c        @ @  B. 0i   r@;2T 2r       ;
--                                                               ;F   B;           :tr;rC; B    @D        6c B:          c Bxd  TBr:   B;r,.        s:
--                                                               T@ .CH                   B2   Zb             B          # @;   B .xE.r@  :rjEr,  ;6 r
--                                                               .2,6nr                   @    @;             @: r       B B2d.Ht     @       ,,6;Srrx
--                                                               si              @@       B;  ;dU              @ @      ijr@  :@      B         T7U   
--                                                               r8                       @X  5;n           n  B        @ @B   B       ;sU@t   igB. . 
--                                                               :g               5;      ;@  c U;          r  rB      ;C Br   5B     ;@#  FB@,@Z;nx. 
--                                                                D               X       .B   B @            r#       B 6@   ;r7Od, Bg r8L   tn;: ;TP
--                                                                n,           .:  ;;:sXn; @   rc d      .   @E       @  @:  UT  ;LrE@    ,2BT   jBr. 
--                                        .                       @Z@gr:;.;::;@L2cLir5xr;T g@   xxSL    @  n@  ;H   EB  @;  xT . j  @ Er.H   ;FB5   c;
--                                                                @  jB@dHFis@s .,          X@ j;cs;8;    BC      Os  x@.   r;D@ 2  B Z;  B     :Hg;  
--                                                                @          rT              i@:   n2gEr.B   .;rr x, @@     Z    2 tj ;:5BS        .;5
--                                                                BT          B   Bi           B6r   ,r@BrstTUB@jx TBb      B  ;.@  B   i:           D
--                                                               .@@i         @;  U:             rO6T..,irOZFUP@@B;@D       @5T;  @:;t              :s
--                                                                @@.r;        B                     r;;,;:;;n;   #E         t     @r 5xr           8 
--                                                                 dc.:rT,     iF :;r,:;..                       B@           B. .x CO  i#n         @ 
--                                                                  CBci;r;;r;tcrr;.  ns,cc;r:rc;:..:;:.:.r     Bg             gr D; t@   :@0,     ;@ 
--                                                                   Bg sO@gLc2L;. ,7s::;.. .  .,..;crr:,,@;j.rB:               gc    ,B     rt,   B. 
--                                                                    8# .r  ;  ;@Si   sd6; :,;r,;;.  rr;F,:r6B;                 cn  :  86.i;.r#B@ @:@
--                                                                      @#c@Dstj. ;.ii@ 8  B .X   . br; .,D  :                    .irrcircrrri;,.cDBT.
--                                                                   . ,2  @   ;;jLr    B #X rr   ;CBC    ;t                                          
--                                                                  :L@8Oi8BLx      @;  @  n i.  B0Z D; #n@                                           
--                                                                 jB i   B s#B      Cn B .g 8 r@O6, BB:,@;                                           
--                                                                  @7Z  in XZ0       d5c iB 8TBr  8;d,; @#;                                          
--                                                                   FBgB.6@@BL        sBt .P@    .@ ,x@  DC                                          
--                                                                   .X # U2, @          xBBs     ;B  @ @ @r@                                         
--                                                                   B #s B@  D@           ,      L@  @ ri 8 :                                        
--                                                                 Z@BO  ;gB   @                  @;  rs B OrB                                        
--                                                                c;:c52gEj#BbtDBjs,.            tc :jtb. B 2;X                                       
--                            .                                   @ @     L, Ed :T;i@           @B@@@i  @ ;7 n Sr                                     
--                                                               @ ,X     @; @     @           @B        @ D  B .Z                                    
--                                                              @  B      @  B   :@           ;r:        E@ @  Br ic.                                 
--                                                           .X@  B       B B@  T@               @B@      BX @  Xx  :;7r::; ;c                        
--                                                     ;sB@BBd  ,@       Bj @  B@              .0: :@B.    B: @   LT,    : n@S                        
--                                                     @,     :@g       x@ @: B@                 :Bi ;B@    gi;nZc  cnUi  :@ r                        
--                                                    ;Z . ;gBS      ;CB@ @F 85                   r Cr sBj   ,ri F@r   ,@BT Pr                        
--                                                    5r @i@B  ;. :nB@ r.   Br                        r: 0E8     6 8HCrC  ,CH                         
--                                                    jDPrjE j@ TB BD @BZ rB                            TP  FO  ;r: .S:Z0Bs,                          
--                                                     r,:;Ds;; ;s.ig;# BCB                                ;TjB;B T@s;:                               
--                                                             .  i. : ,;.                                  ;   L;                                    
--                                                                                                                                                    
--                                                                                                                                                  . 
--                                                                                                                                                      
--  B@B@B@B@B@B   B@B         B@B  @B@B@B@@@B@B   B@B@B@@@B@B@   rB@B@B@B@@    @B@B@B@B@Br       r@@B@B       B@B@B,    ;@B;  B@B     B@B@              
--  @B@;xtxT5B@B  @B@         @B@  B@B@B@B@B@B@   @B@B@8@B@B@B  jB@B@B@B@B@@  ,B@@@B@B@B@B:      @@B@B@B      @B@B@Bg   #B@E  @B@   @B@B,               
--  B@B      @@;  B@B         B@@       B@x            #B@@@    B@@      ;U@   @B@     @B@      B@B  XB@B     B@B B@B@  x@BT  B@B@b@@@i                 
--  @@@B@B@B@B@   @B@         @@@      :@B@          B@B@X      @B@            B@B@B@B@@@g     B@B@   @B@B    @B@  B@B@ ;B@c  @@@@@B@B                  
--  B@@      @B@  B@B         B@B      :B@D       i@B@B@        B@B@     @B@.  @B@7OZOs@B@    B@B@B@@@B@B@c   B@B   x@@@.@Bj  @@B   @@B@                
--  @B@@@B@B@B@B  @B@@@B@B@B  @@@      t@B@      .@B@B@B@B@@@@   @@B@B@B@B@B  ;B@B     B@@B  B@B@      ;@B@:  @B@    .@B@B@B  @B@    X@@@B              
--                                                                                           ;             :                             r:
--
--
--                                                                                                     .Y..                                 
--                                                                                 .:vXgdBBQKgs.     XQq.i:vJ                               
--                                                                          ..KRBBBBBBBBBEX1BBBD1.:1BBP:7:7YQ2X.                            
--                                                                    iY7BBBQBQBBBBBdr     5QL..rBQBB   7Md1QgQ:                            
--                                                                 YgBBQBQBQBQBBu::         K    UBBR   7UPQB.B:                            
--                                                           rYRQBQBQBMBQBBBi77.            M    PBBQ   . iBL77.                            
--                                                      .iMBBQQQBQBQBQBQQgi       i:.       BuJSBBBBB  ... .i .r                            
--                                                :bv:rZQBQBQBgBQBPBQE:         qBQBQB:.iUuU.7iSr7QqrrKBBBQKvJ5ggB                          
--                                      .:. .vZQBQBBBRBQBQqiBQBQr.      rIqY:  Sq.XBBQDPI:  .ui  .r PQBBBQBBBQBQQ:                          
--                               .::.rPJqdgdEBQBQBZBPgBBQBQBRP:      rYUQBBBQB:Q:.:jr.     .dU   P  :siIBBBBQBQLB.                          
--                      .     .KSIBQMQJBgsiUBBQDBMQdDQBQBQQs.       :q    IBBgKii:JL       ig   2v :U5: .QBgB2gEBB.                         
--                   rBBQgI7riULiQK7MZ7BQS7BMBZQRBQBQBQZ:    :LdQBBQR  :77ri..   :d        75   E  s7I   i jIB.BIBD                         
--            7:IJu5BQB7iUgXIiJrgLsRrvBddMBBBQBQBQBPY.      Qi  vQBQBiuuY:.      P5       .vI   Z  i71  g   uQiZvQB                         
--       . ..QZdSiIBEP1rr1Mq.1vYYdq.rD52dP5BQ5YSir         P.  :7dji.:.          d7        7s   Q  YIJ .B   iB:ELBQ                         
--      rrJK1s7uJj571IQE vBviQ:UMvB.UQBBB2d.         .::7r:R2YqYZ                U7        iY   Dr .1iDPBQi.2B BYQB                         
--    .B sq::7.Yi5 ..IBBvvQgdb5PDggBQDbLiX     ..IRIrPPMbPqP:  j.                Su ::irr1Y:U    B  i17vMBQBB.2BqBP                         
--    QdJgv.:.rr17 5i7Q2B:sIDr7E.Ysru7r:    .jRRP:.idZr.  U   :K          i..:vr1SB:17I7KuugQL   .QiQ1i:ii:rvqBuBQ                          
--    QSgQqi::77YQ.L:Ug:.QSMggEXrIUr..  .L2QQB7: iqj     2.   v:   .::vviqQUJJ5uIvd5:vXPbgXv5B:   .IKXRP7EQBBBIZQQrEX                       
--    .rirKZKJB:KgErrLQBEPj1dPQPJ.:    U:  L5   Lq.      P    Ld7S7JjSP2qPEXUvri7JsKEQBb.E.s::B.    :2QBBQBQYiMQBQBQi                       
--   vr.j1Ud.rQuu5EBJJ25DB7:          QY.irU.JQ q:     ::s:YvPYQPduSrr727vs1KPEBQBQBQi7v : vBr:BX   .u:LgBEREBQBBBQB                        
--    iijDU  .X1BrU2PIRUi       . ..:.BUQ.B :gBiS...7rYsR7Z7MBjrIIgZgdQRQQBggqBQBQBQ:  1   :BQE BQv     7qZvbMBBRXBZr:                      
--        .     .i        .UQBQBZQurrBQ K Qi YQjQKZDEDEUQBQgvviBQBBQ7BQBBBQBQBQPJL:. UBBM1srBBQB LBBPu:i:77UQBuBBi:Qd                       
--                     :PQBQ.IP      YB E Ki:iBiKSBBBRBddvX: 71Qu7B LQMdBDQQBr:     YrX.vbBQjQBBB::QBQBQBQBQi rBBQ2iBQ.                     
--                 :SQQQL5i. r   .:ii uii:.UsSQBQM:  :       .QB EQ QB     UBr      B : rBQu5BQBBBX..  .BBQB .QBQBQd:Bq                     
--             .vvBsb7irq.  BvrYJv7:7..D   Pj QQBr  .J7qEDBdr rQ.L. s   iZr BQ      P.7  1BuBQBBBQBQK7  BBBQ  BBBQBQBDSv..LYi               
--          :uJriJrr:Y iQ  .dr..    .v Dr. :2 .L.JPBBBQPLgQBBBiUr:.i:rQY:BQ BB       BQ:  LBLXqKSXvIK ..1Li::dQBQBBQ.iJMB: :B               
--      v5J7Bqrq7Q25SQ7 B.  Prv:irir:i IBBBvi:i  .BQBg.iQBBZBMBgBIBQBQP: gv BQ     .ruZXs..                iBQBBBQB2  rvJis.BLriii.         
-- r7qdUQBYXP2QB qvr::  Q:  UK. .. .i7 r:gQ17S. :7BBQ riILrs::   .rBBBY  gd QB     .DdZbvgDBQ. rKBBUMQZBgb1QQi.v2  ..j7K:iv7:vrriPBE        
-- Ri7Y2 RS .:   u:     Q:  j:. .   .  ir7BPiQ.XY1r:. i:   7s .:   UuUi  QB:7B.     7vqv 1BQBQBBqLXQi    7i       .ri   EL        BQ        
-- Qr7ur:7r:7i.7:gR7sXBQ1BEPg:v2.:ZL.:I  B: ruB..  :        ...7. :BBBQ .Q   B      vL  :BBBQBQB:  P     gg ZYE   :i 1Q7  SPE7vv.:QU        
--:MQSBEgQuKZ7BQBqIS77BQK7vQB vIRYgBBB51grE. .7 B i:v         :r.i:vS.i.:.:r:Qi     ri.  gBBBQBB:  7     .Kii.:  i qBKd Y iQrPBQ.           
--budQiibU7777.ir7iqIqYbQ7iJX2 vJqM.Q7 RXSI: 1Q 7 :.5         gr     :75117s: YBb7v1J:ii.B 7QBBBQBBBQBBB     : i . BB d1L :i .BP            
--PSvZ55BJBRQiMbsI.v57vv:r2Ssqd5rUDiQ77BBBQQYBBZBE:...  r...  L r        :..: 5EBgBQRBgi j  YQQQBQBQBBBvQQ2..sB5Q2K.:i.qBQDQB:              
-- .  .775sK7gQZP12PusE2.L.QvrsPKviiru7XLLrLX2LdZQBdv. :.. .            .:   :Qv.BQBBQ.SQg5BBBQZQQQRDB  BBi  L2Qid:K L.::uBBQBQY            
--          1Kr:7vLDZ7PI1XuRY 7ivgX7sBrviiSbr...:.BKI:ru. . 7   .i   .. i:. rDBQ YQi   QBBBZMQP BZi:BQ  BQ.  Q QdiR.b:7.B7.UBQBQs           
--                 r vM7rrSErJvuSbIBYKPr:rbiY1Js.g7Prs2Y. ..7rr2i.::i::.r7:.iBQBq... vQBgBQBgQQ DB.Pr  7QBJ7rgs Qb7B.M2ui:d  BgB:           
--                   :.irIP.1Quqi7v5:XDP5 BvB7iQDBiBUZvQjSX1..  17Y.:vBdL:r:::.irirsdQqSBQBBBgBQ.r:   iQBQi7Lri  . .           Pv..         
--                     : iB.su.D:: K.M Yq.UiQJ.rrr.D.5rrQKbBQY:1jIQSrLvY   iv1YQDQbii:... .. .:v7..JJBQBQQ SuKXRdXqdgBDQZQUdDg5BSuJSIXIUrvJ:
--                        .  i :iP5 Bur7E:jiUbr7gXdiiri7di.gPjQvg1:SIQBQEXBQsPPIIL.   :r2rvPP7vv5PqXSi:::.SZQQBQBQBBBQBQBQBQBQBq5BBBBQBBBs  
--                                : . .i:D r.7:QYiS.ibIvBiYdrBURii7siKBrjb2B.SBZPUPdsRBjBEvBQQQs..   ri7vKv7.::.:i::.::i:vv1:L1dQBBgL:iqZ57 
--                                        i  7 : .B2:1bLsrr:Pj Z:X5:v i5udQ:.gBr7JIgBQ.v7XJIiDXU. J1KSBBM1BQqBBMD:777v5i:i:.i:ir7rr.        
--                                                 ...i Yu  Pii1gv2u7ZP:QUBiPBMXZ.PBY5KggSiSiJiBQBXrSrqB5X.LRPur.:.77EMBQBQBBBZKi:r:        
--                                                          :.     i: u.vi:LJi.r:7.i: :IS:SrB:J..Bi IQ.d:5UrBBr7BQBgB7jr2vB:2:              
--                                                                                                    .  v   :. . .                          
----New series of simple scripts that just work..nothing fancy 
                                      


if myHero.charName ~= "Blitzcrank" then return end
