----New series of simple scripts that just work..nothing fancy                                                                                                                       
-- 
--
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                   T@P .s#@@@#c.                                                                                
--                                Y@@@2 9@@@@@@@@@8                                                                               
--                              h@@@@; @@@@@@@@@@@@@                                                                              
--                            C@@@@@P @@@@@@@@@@@@@@@                                                                             
--                           TS   5@, @@@@@@@@@@@@@@@                                                                             
--                                h@7 @@@@@@@@@@@@@@@                                                                             
--                        Cs    ;@@@ :@@@@@@@@@@@@@@Y                                                                             
--                      #@@@@9M@@@s   @@@@@@@@@@@@@7                                                                              
--                    ;@@Y     ;7  ;@ C@@@@@@@@@U.     .                                                                          
--                   ;@.          Y@@  ;@@@@@@@@7;Cb@@@@@@@ME;           Y2;GY                                                    
--                   , CM7  #@dCG@@@7    0@@@@@@@@@@@@@@@@@@@@@@@P;   7b@@@@@@O                                                   
--                   Y@@  1@@@@@@E           ;2@@@@@@@@@@@@@@@@@@@@@ZZ@@@@@@@@@@7                                                 
--                  D@D  G@;  G@;                cM@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@s:                                               
--                 5@@  ;@                          ;YFl;;X@@@@@@@@@@@@@@@@@@@@@@@X                                               
--                 :@T  U.                                 ,#@@@@@@@@@@@@@@@@@@@@@Z                                               
--                  @   .                                    .F@@@@@@@@@@@@@@@@@@@@@                                              
--                  s .                                         @@@@@@@@@@@@@@@@@@@5                                              
--                   7U                                          5@@@@@@@@@@@@@@@@@@@T                                            
--                 ;E@.                                            .0@@@@@@@@@@@@@@@@@@@;                                         
--                c@@7                                              .@@@@@@@@@@@@@@@@@@@@b                                        
--                @@:                                              ,s@@@@@@@@@@@@@@@@@@@@@@                                       
--               ,@                                              7@@@@@@@@@@@@@@@@@@@@@@@@@#                                      
--               ;E                                             .@@@@@@@@@@@@@@@@@@@@@@@@@@@;                                     
--                7                                             Z@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                     
--                                                              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                     
--                                                             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@;                                     
--                                                           .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                      
--                                                          7@@@@@@@@@@T P@@@@@@@@@@@@@@@@@@                                      
--                                                         s@@@@@@@@@M    7@@@@@@@@@@@@@@@@@                                      
--                                                       7@@@@@@@@G7.       @@@@@@@@@@@@@@@@                                      
--                                                      .@@@@@@@@E          @@@@@@@@@@@@@@@@Y                                     
--                                                      @@@@@@@@@          @@@@@@@@@@@@@@@@@@                                     
--                                                     v@@@@@@@@d         7@@@@@@@@@@@@@@@@@@1                                    
--                                                     @@@@@@@@5          8@@@@@@@@@@@@@@@@@@@                                    
--                                                    @@@@@@#7          7@@@@@@@@@@@@@@@@@@@@@                                    
--                                                   2@@@@P            7@@@@@@@@@@@@@@@@@@@@@@.                                   
--                                                 7@@@@@             b@@@@@@@@@@@@@@@@@@@@@@@7                                   
--                                            ;7Z8@@@@@@@G           7@@@@@@@@@@@@@@@@@@@@@@@@@                                   
--                                           ;@@@@@@@@@M@@@@:      7@@@@@@@@@@@@@@@@@@@@@@@@@@F                                   
--                                           ;OU@@MM@h   ,7:      G@@@@@@@@@@@@@@@@@@@@@@@@@                                      
--                                             .7  1,             @@@@@@@@@@@@@@@@@@@@@@@@@@,                                     
--                                                                @@@@@@@@@@@@@@@@@@@@@@@@@@@                                     
--                                                               @@@@@@@@@@@@@@@@@@@@@@@@@@@@                                     
--                                   ;h@D.                     ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@Z                                     
--                                 :@@@@@@c      .;G@@@@@hY.  ;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,                                     
--                              ,75@@@@@@@@@FP@@@@@@@@@@@@@@Mv@@@@@@@@@@@@@@@@@@@@@@@@@@@@@d                                      
--                             b@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;                                      
--                           T@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:                                      
--                          E@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;                                      
--                         c@@@@@@@@@MSvO@@7   ,75D@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@5                                      
--                         @@@@@s7,       7          :5@@@@@dGZM@@@@#7:Y7M@@@@@@@@@@@@@@@@@@                                      
--                         7@@P                                          ,@@@@@@@@@@@@@@@@@@                                      
--                                                 .           ,C@@@@@8Z; d@@@@@@@@@@@@@@@@@                                      
--                                               C@@@7      7h@@@@@@@@@@@@@@@@@@@@@@@X1s7:                                        
--                                              @@@@@@@ZE@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                             
--                                           7F@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@T                                             
--                                         ;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@P                                              
--                                        5@@@@@@@@@@@@@D#@@@@@@@@@@@@@@@@@@@@@@@@2                                               
--                                       :@@@@@@@@@@@@@@           ;71c;.   .::.                                                  
--                                       8@@@@@@DT:   1Y                                                                          
--                                       @@@@O                                                                                    
--                                       @@@S                                                                                     
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                                                                                                                                
--                              b@@@@@@@@@@@,       @@@@@@@@.    M@@@@@@@@@@@@MC.                                                 
--                             S@@@@@@@@@@@@       Z@@@@@@@1    ;@@@@@@@@@@@@@@@@:                                                
--                            ;@@@@@@@@@@@@Y      .@@@@@@@@     @@@@@@@@@@@@@@@@@2                                                
--                            @@@@@@@@@@@@@       8@@@@@@@:    s@@@@@@@s v@@@@@@@;                                                
--                           @@@@@@#d@@@@@@      ;@@@@@@@D     @@@@@@@@  7@@@@@@@                                                 
--                          D@@@@@@;8@@@@@v      @@@@@@@@     Z@@@@@@@;  @@@@@@@;                                                 
--        2SS5S51c7:       l@@@@@@:;@@@@@@      T@@@@@@@2    .@@@@@@@O  d@@@@@@G   7GFUd7   5UOU#  5ZCEd.    ;FM@@@#5             
--       l@@@@@@@@@@@     ;@@@@@@2 @@@@@@@      @@@@@@@@     @@@@@@@@Us@@@@@@@P    @@@@@   ;@@@@@ :@@@@@   7@@@@@@@@@@            
--       @@@@@,l@@@@@     @@@@@@@ ;@@@@@@Y     Z@@@@@@@7    7@@@@@@@@@@@@@bCv,    P@@@@;   @@@@@  @@@@@   v@@@@. @@@@@            
--      X@@@@: 7@@@@7    @@@@@@@  @@@@@@@     .@@@@@@@@     @@@@@@@@@@@@@@bl     .@@@@@   7@@@@1 7@@@@s  .@@@@7  @@@@7            
--      @@@@8  @@@@@    d@@@@@@; .@@@@@@@     @@@@@@@@.    l@@@@@@@c S@@@@@@@    @@@@@.   @@@@@  @@@@@   h@@@@Z                   
--     @@@@@  E@@@@:   l@@@@@@5  G@@@@@@v    7@@@@@@@9     @@@@@@@@  s@@@@@@@   ;@@@@Z   U@@@@; F@@@@;   #@@@@@@F                 
--    ;@@@@F  @@@@b   ;@@@@@@@M@@@@@@@@@     @@@@@@@@     h@@@@@@@;  @@@@@@@:   @@@@@    @@@@M  @@@@@     X@@@@@@@Y               
--    @@@@@  @@@@@    @@@@@@@@@@@@@@@@@@    l@@@@@@@l    ,@@@@@@@@  d@@@@@@#   1@@@@Y   #@@@@  @@@@@        X@@@@@@               
--   l@@@@7 ;@@@@S   @@@@@@@@@@@@@@@@@@s    @@@@@@@@     @@@@@@@@  :@@@@@@@    @@@@@   ;@@@@G ;@@@@F   FO5X: ;@@@@@               
--   @@@@b  @@@@@   9@@@@@@@7. h@@@@@@@    D@@@@@@@;    7@@@@@@@F  @@@@@@@C   9@@@@;   @@@@@  @@@@@   c@@@@  ;@@@@:               
--  d@@@@; b@@@@;  s@@@@@@@Z   @@@@@@@@   :@@@@@@@@     @@@@@@@@  v@@@@@@@   ,@@@@8   7@@@@l 5@@@@;   @@@@G  @@@@X                
-- 7@@@@@@@@@@@c  7@@@@@@@@   h@@@@@@@5   @@@@@@@@     8@@@@@@@c  @@@@@@@7   @@@@@    7@@@@@@@@@@:    @@@@@@@@@@S                 
-- 9@DDh#d#9O7    @@bDDh#b:   @M#hh0#@.  ;@#dhhhM5    .@@DD0ddd  s@dD0D#h   ;@d9#s     :9@@@@@F:      .F@@@@@E7                   
--                                                                                                                                
--                                                                                                                                                                                        
--                                                                                                                                
--                                                                                                                                     
--                                                                                                     .Y..                                 
--                                                                                 .:vXgdBBQKgs.     XQq.i:vJ                               
--                                                                          ..KRBBBBBBBBBEX1BBBD1.:1BBP:7:7YQ2X.                            
--                                                                    iY7BBBQBQBBBBBdr     5QL..rBQBB   7Md1QgQ:                            
--                                                                 YgBBQBQBQBQBBu::         K    UBBR   7UPQB.B:                            
--                                                           rYRQBQBQBMBQBBBi77.            M    PBBQ   . iBL77.                            
--                                                      .iMBBQQQBQBQBQBQQgi       i:.       BuJSBBBBB  ... .i .r                            
--                                                :bv:rZQBQBQBgBQBPBQE:         qBQBQB:.iUuU.7iSr7QqrrKBBBQKvJ5ggB                          
--                                      .:. .vZQBQBBBRBQBQqiBQBQr.      rIqY:  Sq.XBBQDPI:  .ui  .r PQBBBQBBBQBQQ:                          
--                               .::.rPJqdgdEBQBQBZBPgBBQBQBRP:      rYUQBBBQB:Q:.:jr.     .dU   P  :siIBBBBQBQLB.                          
--                      .     .KSIBQMQJBgsiUBBQDBMQdDQBQBQQs.       :q    IBBgKii:JL       ig   2v :U5: .QBgB2gEBB.                         
--                   rBBQgI7riULiQK7MZ7BQS7BMBZQRBQBQBQZ:    :LdQBBQR  :77ri..   :d        75   E  s7I   i jIB.BIBD                         
--            7:IJu5BQB7iUgXIiJrgLsRrvBddMBBBQBQBQBPY.      Qi  vQBQBiuuY:.      P5       .vI   Z  i71  g   uQiZvQB                         
--       . ..QZdSiIBEP1rr1Mq.1vYYdq.rD52dP5BQ5YSir         P.  :7dji.:.          d7        7s   Q  YIJ .B   iB:ELBQ                         
--      rrJK1s7uJj571IQE vBviQ:UMvB.UQBBB2d.         .::7r:R2YqYZ                U7        iY   Dr .1iDPBQi.2B BYQB                         
--    .B sq::7.Yi5 ..IBBvvQgdb5PDggBQDbLiX     ..IRIrPPMbPqP:  j.                Su ::irr1Y:U    B  i17vMBQBB.2BqBP                         
--    QdJgv.:.rr17 5i7Q2B:sIDr7E.Ysru7r:    .jRRP:.idZr.  U   :K          i..:vr1SB:17I7KuugQL   .QiQ1i:ii:rvqBuBQ                          
--    QSgQqi::77YQ.L:Ug:.QSMggEXrIUr..  .L2QQB7: iqj     2.   v:   .::vviqQUJJ5uIvd5:vXPbgXv5B:   .IKXRP7EQBBBIZQQrEX                       
--    .rirKZKJB:KgErrLQBEPj1dPQPJ.:    U:  L5   Lq.      P    Ld7S7JjSP2qPEXUvri7JsKEQBb.E.s::B.    :2QBBQBQYiMQBQBQi                       
--   vr.j1Ud.rQuu5EBJJ25DB7:          QY.irU.JQ q:     ::s:YvPYQPduSrr727vs1KPEBQBQBQi7v : vBr:BX   .u:LgBEREBQBBBQB                        
--    iijDU  .X1BrU2PIRUi       . ..:.BUQ.B :gBiS...7rYsR7Z7MBjrIIgZgdQRQQBggqBQBQBQ:  1   :BQE BQv     7qZvbMBBRXBZr:                      
--        .     .i        .UQBQBZQurrBQ K Qi YQjQKZDEDEUQBQgvviBQBBQ7BQBBBQBQBQPJL:. UBBM1srBBQB LBBPu:i:77UQBuBBi:Qd                       
--                     :PQBQ.IP      YB E Ki:iBiKSBBBRBddvX: 71Qu7B LQMdBDQQBr:     YrX.vbBQjQBBB::QBQBQBQBQi rBBQ2iBQ.                     
--                 :SQQQL5i. r   .:ii uii:.UsSQBQM:  :       .QB EQ QB     UBr      B : rBQu5BQBBBX..  .BBQB .QBQBQd:Bq                     
--             .vvBsb7irq.  BvrYJv7:7..D   Pj QQBr  .J7qEDBdr rQ.L. s   iZr BQ      P.7  1BuBQBBBQBQK7  BBBQ  BBBQBQBDSv..LYi               
--          :uJriJrr:Y iQ  .dr..    .v Dr. :2 .L.JPBBBQPLgQBBBiUr:.i:rQY:BQ BB       BQ:  LBLXqKSXvIK ..1Li::dQBQBBQ.iJMB: :B               
--      v5J7Bqrq7Q25SQ7 B.  Prv:irir:i IBBBvi:i  .BQBg.iQBBZBMBgBIBQBQP: gv BQ     .ruZXs..                iBQBBBQB2  rvJis.BLriii.         
-- r7qdUQBYXP2QB qvr::  Q:  UK. .. .i7 r:gQ17S. :7BBQ riILrs::   .rBBBY  gd QB     .DdZbvgDBQ. rKBBUMQZBgb1QQi.v2  ..j7K:iv7:vrriPBE        
-- Ri7Y2 RS .:   u:     Q:  j:. .   .  ir7BPiQ.XY1r:. i:   7s .:   UuUi  QB:7B.     7vqv 1BQBQBBqLXQi    7i       .ri   EL        BQ        
-- Qr7ur:7r:7i.7:gR7sXBQ1BEPg:v2.:ZL.:I  B: ruB..  :        ...7. :BBBQ .Q   B      vL  :BBBQBQB:  P     gg ZYE   :i 1Q7  SPE7vv.:QU        
--:MQSBEgQuKZ7BQBqIS77BQK7vQB vIRYgBBB51grE. .7 B i:v         :r.i:vS.i.:.:r:Qi     ri.  gBBBQBB:  7     .Kii.:  i qBKd Y iQrPBQ.           
--budQiibU7777.ir7iqIqYbQ7iJX2 vJqM.Q7 RXSI: 1Q 7 :.5         gr     :75117s: YBb7v1J:ii.B 7QBBBQBBBQBBB     : i . BB d1L :i .BP            
--PSvZ55BJBRQiMbsI.v57vv:r2Ssqd5rUDiQ77BBBQQYBBZBE:...  r...  L r        :..: 5EBgBQRBgi j  YQQQBQBQBBBvQQ2..sB5Q2K.:i.qBQDQB:              
-- .  .775sK7gQZP12PusE2.L.QvrsPKviiru7XLLrLX2LdZQBdv. :.. .            .:   :Qv.BQBBQ.SQg5BBBQZQQQRDB  BBi  L2Qid:K L.::uBBQBQY            
--          1Kr:7vLDZ7PI1XuRY 7ivgX7sBrviiSbr...:.BKI:ru. . 7   .i   .. i:. rDBQ YQi   QBBBZMQP BZi:BQ  BQ.  Q QdiR.b:7.B7.UBQBQs           
--                 r vM7rrSErJvuSbIBYKPr:rbiY1Js.g7Prs2Y. ..7rr2i.::i::.r7:.iBQBq... vQBgBQBgQQ DB.Pr  7QBJ7rgs Qb7B.M2ui:d  BgB:           
--                   :.irIP.1Quqi7v5:XDP5 BvB7iQDBiBUZvQjSX1..  17Y.:vBdL:r:::.irirsdQqSBQBBBgBQ.r:   iQBQi7Lri  . .           Pv..         
--                     : iB.su.D:: K.M Yq.UiQJ.rrr.D.5rrQKbBQY:1jIQSrLvY   iv1YQDQbii:... .. .:v7..JJBQBQQ SuKXRdXqdgBDQZQUdDg5BSuJSIXIUrvJ:
--                        .  i :iP5 Bur7E:jiUbr7gXdiiri7di.gPjQvg1:SIQBQEXBQsPPIIL.   :r2rvPP7vv5PqXSi:::.SZQQBQBQBBBQBQBQBQBQBq5BBBBQBBBs  
--                                : . .i:D r.7:QYiS.ibIvBiYdrBURii7siKBrjb2B.SBZPUPdsRBjBEvBQQQs..   ri7vKv7.::.:i::.::i:vv1:L1dQBBgL:iqZ57 
--                                        i  7 : .B2:1bLsrr:Pj Z:X5:v i5udQ:.gBr7JIgBQ.v7XJIiDXU. J1KSBBM1BQqBBMD:777v5i:i:.i:ir7rr.        
--                                                 ...i Yu  Pii1gv2u7ZP:QUBiPBMXZ.PBY5KggSiSiJiBQBXrSrqB5X.LRPur.:.77EMBQBQBBBZKi:r:        
--                                                          :.     i: u.vi:LJi.r:7.i: :IS:SrB:J..Bi IQ.d:5UrBBr7BQBgB7jr2vB:2:              
--                                                                                                    .  v   :. . .                          
----New series of simple scripts that just work..nothing fancy 

if myHero.charName ~= "Darius" then return end
