----New series of simple scripts that just work..nothing fancy                                       
--
--.                                                                       xUXc                                                                          
--                                                                         ;s2c.       :                                                                
--.                                                              ;.         ,ssUtc;    rB2                                                              
--                                                               ,#@Hc;,      csZUcT:  ,S6g                                                             
--.                                                                t@B@BD2r    C;iLjTt..ssSF   .                                                        
--                                                                  ;@BbbHDgr   U:cFcc0FrjsPF  .       ...                                              
--                                                                   rUnSPng@tr ri:7T;CUr7LSn:   .rtnsOnSxxstSntncr:                                    
--                                                .rtXZXF2xStj7r:,    rsCU27Fdntrc:;rriTrs5ssrTs5Fr;:;rrr;;;;:,:;rr506t:                                
--                                            ,cgXZs7:.     ..::;ricT;rr5US5rrO0jr:.;rrx7L5TiF0r.;c5OCjjsccrjstcirir;;rLZ;                              
--                                         ;tCi;.  .:rit5nCFS5jr;:.,,cgSrxgins;tZs;..r7s;s5nPL  g@Sr;,..       ..;rTCnc: r0;                            
--                                      ,SUi.  ;jF6ggOX5Lrr;rrrrccCc:  ;XsLX;Lcrsnxr,.rL;7CB; .bB;,.:::,,....       .;LXU  0r                           
--                                     Zb;  ;O8B0Cr;;,.      . ..,:s2;   Z;rC;crrxOt;,:5irZS .7@,,::,,,.,... .       ..;Xn  8,                          
--                                   c@7  rd8Fi;:,,.. ..,..         xL.  TO:ixiL;rLnr;rrr;B8.,rPr.                    . rn: Ct                          
--                                 ,F@;  sdn;, ..,,,.              ;;,.  dPrxTLxc7r57rU;.;B@L. ,iTi.                    ri. Zr                          
--                                tFdj .;UX;.   ..,             ,;:    .cB; ;cZji,;;5rci;r@:;gT   ;rr;               .:;; .,H;                          
--                              x0c 5c.;::;;;;;;:;.... . . .        ;r;rbB, .rj2n0Pd@DXC7g; rC@@X;    .,:r7r;.  .,;rc7;. .:,isO.                        
--                           ,SPc..:5Xjr;...,,,.,,...           .;r;, .#bini.j@#PCi;;;;. s;jHtTcFb#xc.  ;. ,:;i         rc :r5St                        
--                         rFi   rtXiLOO5tciiT;,........:;:Lci5x7;   xBd;;0x:CP,     .   ; cX2ZP5rrTi;c0  ..;  L;,,;rcSO87;r2@Xg                        
--                            .;cOdx,:LXdXZSFSXZnCCcirr;;;UL     .rrPXr:r50nr7i .;LCOSXt;r ;x:rTxxFxc:Sc gi ;2 x;  ;7tC;r7,FcscX                        
--                          :srCHX0i  ,,rg;;r;;rr;;r;;,..s. ;i;.  ,t;..cO2Zx;rsgB@Bdn5L088rsSrrir;:;;rZ2;Zr;jg.ZrrcTLcir,FnSct5;                        
--                         tUi2PtZB;  i. scrr;;;;rrrrr;,;i .XrrsC; .rrEBBB@B8B@B#06ZFjr,TOPFT;;rTir;;:iLr;CUXrrL,        .rs5s;.;;,                     
--                       ;Ctjt7t8D6C .75 tF7cLTsTLjirr;r;STTBj;;nL;ssr5sijsZFPEPjcF2XPCiiitO#Frr;rj2r;.,ii:;r5T;rr;rrrrr;;;is@Br.. :,.                  
--                     ,rscTi;OB8SgU7gXLgxr;7rrrrrr;::::;rUcxZssU;jUgFts5xStCsxCUCSC200istLL8B@SSb@bL;cr;:;iscj7j7rrCL:,:;riTs@BPi,                     
--                   ,irc6Xi;n86ZsZ0bUrLsr;rrcTsLLTsLsccir;ri7rr;xDxUBHDd6EgXH6ZCUF0Oc#FrFTTSBnXbB6D00#BgUUP0OCStxS02iE0O5COxji2B86#L.                  
--                 ;tT:;FgTrUggFSrFDPc;.csc,    ,.,,:,,.   ,Lsss5cr;;;;:, .,;TL5CcXZtxg67C6UnciLcrisOB@B6OF5i;;;r760s;5XOjcsXtcscg@b0sLcr;.             
--              :jji:  ZdirtxxxSjLF#SccrS@b8PgFc;;...:,;;;:.,;cEUCrrctrr:       .;iDSc5n0#Tcc;;;;cLSEs:.,;.. .;5d@BH0Z5Usj;rsnCs5ntEE:   ;;:..          
--           :r;,     tBjTSCtt#tStZ#sT7;0BFCZ6BB@B@BgSSCsiSEPPXT5sgExrrrt#@dXxr    .CPiX@tsr;:rcr;;:  .;ssriUHDZ2Cs5SUZtLcjcLcjijr7jn8U,                
--         .         rB2cg2Cc@6ScF8Etg;:SZcCS68B@@B#H6scrUB0CLjiCCr;;CLrXgn6d8B@n:   rb@gi  .::;;Cc7;cSCtsr;;it2ss;.,;:;;;;r;;;ir7LtsjC8S;              
--                  .@Fr8cr50BD7C0HgZ6Tj68dP0X6#dP#8@Ennni;rrrcTTrriS5xZFtSStrsg8B8;  FB#  rrir2OjXnHB@Xr:r;;;r;7g85..rsdB@B@D2sLrTctt550POc:           
--           :.     E676r;igX@jt8UgBC5C6XCjLsxZdDb#@crccrrcFx5cUjicrcXZTjLTLrrt5sBB@B.r@;,#biT;;;;r5rrx@B@HHFr;7r;i@#E0gP6OOnPb8#OjTcsxFnXPdHFc;        
--           ,PB@B6dSsOsrs62dSrcirrcrrrrcc2OUnEZ0D@0xFX5ZEDXtiT;rL;:ns:;r;;.:rrjBB@@@BBBtB@cHjr:;;rc77.;i8@rcgUirr;rB2:;r;;;;;rcSO#0SscTLsCt5LsSZT;     
--              ;CE025r;;j2UsstsTjsscccjxSLOPnxZD#XDEd808P;.:;,;;  ;:  .    r:r2B@DBB@@@B@B;r8;r;:r;:i;rrr6b,.;nDC;:rBL;;irr;;:;;;;cjtcj55Tjc7rristF5Tr 
--               ,FSriLTsri7rrr;;;;;;;ic7igFirCXtL#O0HiTx, .,              :;,sx;.,:;rU@@B@s;gtr;.;.: 7;trCBF,;.PBH;,iPrr;rrir;;:,,,;;;7sLsj5LLir:.     
--             .jHgjcjTXS5FjrrrrrrrTsUZsC#r,t2sssgOFt;.r         .      . ,r,rZr,;;;:,.;:;Xi;rd,...   ;;srjHU,;trr##t,siisc7rrrcrr;r;rrr;;;7rr;ricii;:  
--          :;iXHZ7rTLUU6Ziricicc2Ot68HX8;;F5icgDBsr; .         ..   .r ;;ri;tn,:;;;:::.. c; ;@  .    . s;rTx.rPt,LSHjLr  .   ,:;;rrr;;,....,;rr;.      
--     .:rir;rcrLLrc7icCLTCFndHZxFXdxcx6s.rr7L8DBxr  .   .    .. ...:Tc:rcstrC; ,;:,.:,, ,t. L2 ;.,.    j;;rc:5Sr5;CEFOZ7S5r;, ,       .:;;:.           
--;;P6dXj;;rr;;rLrirr;;r;rsCtTcsCFZcr;sH;.:c7gXxS;  .:. .;,.;,, .::r, gTxr;255:   .   .  ir  B;:;:;.. ,.t;;j;;OTrcxr7Xjxsd@b08DxxEB@@#L:.               
--      ,ri7;,;:;;:;;rrsSSiirisxjj:,;LBs,;x;TOsX;.  ;:. :;;;rrrrcrr:  2gT  ZxL          ;jr.Z@.r;;;;,;,:L;ri jT7trCFrr0LrcTjr;r;;sHSH@BbS7;:.           
--    .rr:,   .,rc55O5sUFisCn5ssFsxn8Bgr;xrrTsLL . :;;  ;rF rtT:Ojr   ;#r  iLi          c;rU@,7c:;r:;;rt;Ts:rdxisjin2,iZ,csTLLr;rrtT;jCxFjsir;ric;;,    
--  7CLLr;;;rLt2xcir;rii;cCH6HB@bPb@BX;;crr5jjt:.,,;;, ;rF; sF. Es     Bc  ,Xi         i;Tit;rtr:;.r;;7c;nrsb@B6i;iLs7 Cr;5rTFtirLrC:;ist2Tx2xLr;.      
--XsP6XnFSU2Z2s7r;rrisUZPEZFxCS;,iDBP: ;;:jSciU:,,::;: ;jS  xc  D:     rt   Z5        ;i0;.rcc;:;:rLrrciiriB@#88@c .sO;;n;Sccj2srijLn;rr;:;:,           
--SsOO2t52sTr;:;;rFHgg2Cr;;rcLr;c8DL, ;;,ctcrCU:.T;rrr ;g   r. ,S       L   rO       iCS. cCr;, ;7;;srxrrXB@EcXXt@s  UC,ccrC7Urn;c57bi                  
--    ......;rrrEdsrrrcrriF2s7;r#Es. , ;CU;irTF ;xrcc, xDXDxPSrsO:,   . ;.   E:    :T;:  F2r;: ,c. irrtr#B08cjLCic@5  2rrT;T7C;i;:S;gP7.                
--       ..;:,. ...:rircccii;,,2UL: ;.:xE,rcrjC.rT;Lr  Xi56XObt2ZUS2Tr,. ... rx   .,   ,ssr;. .s;;c#Z#gPCnCg;Lr7Lr;@0 ;c;rrr7cc:c.jc5OS;,               
--Et5tZc;::;;;;;rcTrrr;,..;;  UBS, ::.LC ;si;ZT.ir;L;:r#8B@BDPOBD2ZC2FPSr..,: ,       ;rr;, ,r8OcrxinUg2OB@Drxr77i;i@t r.::,7i2 r,;LcTxX...             
--cc5CFScTiccircr7rr,  .;7;,,OBg, ;; rL ;Fir;dr:r;rxr2iDsr8x,CnxB..Cn5rsF6t;,;::,;:;;:,;:.;t2t;rcdDSxHd; ;rLrSr7,ti;s@: .::.;ri;;; irc;PZ. ,            
--    .:;;rr: ;;;;. ,;csi;:;UBc  rr ii ;Scs,rXrrr:jrrS5s  @r s#c6  . ;Lc;rLFFrir;;;;;;:;sSjr;rOOEBL;8BUs,  rcSi;,Tr;cs@   ;.;;c;r7,:rLrc0#;  .          
--       .;i;;;:;;rirsiLi;.rP;.;cc.r; ;tLsr,rxr;rrT7rrs5i;X@Fr,,rH@S  ,rsEC5L;;r;;;;;;;iUcLgUr   @Or:r ;B;.STxri;Lrr5ibi .;.;rc;;ts.:i;rEBBE            
--   :cSFc;;:;rr7r7rrcjr, ;Zrrcr; .  ijr;r:;rcU;risjc gc.:;j6B@#dP#Uji7;,.,.  ,:;:;;;;rTicLsjrrrrZ@BnZbbbCd;;.r;iciis;ZP. ..:;sr.isr;r   :C8@r          
--  rxCLrLsUjr:;;:.:;; .;C0;7jr,   .Ls;;: ;;r;Oriic5i L8.                     .,    .;TZr;.    ....;;;;; sT   ,;i;:Ci;S8r  . ;ic:;rir;;     .i.         
--       :cU6nc;r;;;;.;;5S;rr;.   ;xt;;.  r;;:SiictTi  B2                     .:      jr;:,              x,  .,;r :6;rjZn  ..:r;crc;rri                 
--           :rtZOLirr;5C;;:    ,sCr.;   ;rr,;cj;strr  rB ;r;rrrrrrt7,        .:     .i,,;,,.:r7;;;;;r;;0i  .  r, in.irUb  ,.rr;;iTi;:sr                
--                ,;;;OZcii;. ;isTr;;.  ,t;;;;;Zr;Ori   ;;c     7Ft;          .:     ,L,;;,.,.:cXHT,;,;BU:::. ,; ,x,rrrsb. ,;rt ;:Ucc;.Z;               
--               ,;;;cS7txs;.rtLcr;r,  .Cr:r;r.ZUrZri.    i    cT,            .:     :r:::....   rx,  iU;r,.  ;  L;;ir;rZ. :;CS;;:Exrr. i;              
--            ;Lnjjr;cctCr;rscrTcr;    ir;,c:r:5@P6nT,.   i .jF;              ,,     ;i.:.. . .   .SL7Usi;,  ;. ir.;rr;rX, ;iU;;;;xZrr,, .              
--         ,TL5jTr  iixsr;rt,.ijr:    ,C; :r,j:S0XdXt:..  rSL:               .,:     ;r,,. ..   .;: :tC67:  ;r ii,:r7T;U6, rsDi:r;sXLc,:.               
--       ,;;,      iLSs;  ;:,r5r:    .c;  : rr,tCisDg; .  .,                  ..     ;r.: . .      ;crPj:  ;c i5, ;TC;rdO: TZULtr.Tr;ir r               
--                Z2sr   i;:,ns.    ;c:.   :c;;;tc;r6P.                       .      :r..         20;FZ::.rL rt;  TC;;FDnT cXr:En.;r Fs  ;              
--               2E;   :xr  nc  .,,;X;.    :;rr:5sL;rB2                       .      .r:,       rBs rZrcriT.rT. ,5Trsggn6i LO::rUZ;i ;6;  ;             
--              7;    rT.  Cj,.; :,sr     ..;i;:r7xg,;Bc                    .;.       ;;..     Fg. ;nriLsr;xr..:ris0xCjsUi EnirirF2t  SC   :            
--             i.   ,r,   tir;r:;;,r       .;:  rit6C :8r                    ;:,.   .:r;.     ;.  ;jrr:;rcx;;r;rO6DCr5sSZ:;DOxr;2F2xr  8.   .           
--            ;    r:    sittLr7. ;r,      ;.; .LscZ0L ,c,                    .:;:.,:;:.         ,rj: ,rir;risC6E5riSxTgd:tssO6jigEnCr rP               
--                     ;STUSi.    T;.   . ; ., ,icj2n8r ..                                      .;r  r2jsc5x0ZjSLLsjTsOPE;iri rPHFXgF ;.xr              
--                    i0xL;      rr,.. ; r. ,. ;rrtSTDdr.,.                                      . ;SXiiT2gP6jjT7jijxtXFTr;:c:  ;FOPBx   :              
--                  :PZr.        s,,r ;.;, .. ,;crn5CSP#;..                                      :r;. ,7rTnXnst;irrTUtT5cC. Z7    rrj6n                 
--                 c7.          .i.r,,;rr :,..;ir77tCsC0#: .                 ...,:,;;r;,        .,   rnr;c6r;r;;r;cOcrrgT:  Es     ,;r,T                
--                ,             sxr;,7;7.;r,..rjs,;TT;5T0g,          ,bBBP2ci;r;:,;:;;iTscjs6n; . . rL;;;tb,;;;jrrxs:;dd;   U5       c.                 
--                             .6; rsC.r Lr, ;xS7 7Cr;c5s#P, ...       .:rLti;;ritj7rriLtUCSnL:..:.;;.ir DS;r;TLLCi. ZBr    iU        .                 
--                             Si ;CZ,.c:Si.;TP5  ir;;TTcFOH:  ..           .,:..   .:;;;:.   ..::.  rr r0;LCr5Ssc, rBc     ;D                          
--                             t  EPr 7rLj:;sHT  Tcc:;srrCc00r   .             ,,::;:;,. .........  j;  OsiU;5XTir  X6       D                          
--                            L  :@U  STx:iT8r  ,Pc7:;c;;rTiXbj.        . .  .. . ....,.,...,.,.  :;C  ,;OO;iOSrx  ;@        r.                         
--                            ;  rds ;On:j2@;   d7 r,rL;;;rrs0t;;;.          ..,.....,........  ,; ;r   r0;;XCrP.  dj                                   
--                               iO  jBirXb.   U5  r;js;,;;;Z8r, ,;;,         .....     ...   :r:  i,   n;;dFtO;   g                                    
--                               6r :@r gg    sZ   r;jr;.r;r6# r    :;:.           . ....   ,r;    t   .OcHrrOr                                         
--                              :D  @i n7    rt    7sj;;:r:rHi r.     .;:.            .    ;;      7   rBd .dL                                          
--                              cs Cs ,     .;     ;Os.rcc7;n  ;;        ,:,             :,.       r   B6  Pb                                           
--                              0, .                Dr iCrr;s   r           ,;:,,.,...;;:         :;  sD  ;B:                                           
--                              0                   Zr ZU; ;    ;               .,,,              :.  j   Ux                                            
--                             .F                   nr dX       ;                                 ;  :   ,#                                             
--                             :r                   cc HZ                                         . ,    n7                                             
--                                                  ,n cX                                                Z                                              
--                                                   7 .i                                               rc                                              
--                                                      r                                               O                                               
--                                                      :                                               s                                               
--                                                                                                     ,;                                               
--            
--                                                                                                     .Y..                                 
--                                                                                 .:vXgdBBQKgs.     XQq.i:vJ                               
--                                                                          ..KRBBBBBBBBBEX1BBBD1.:1BBP:7:7YQ2X.                            
--                                                                    iY7BBBQBQBBBBBdr     5QL..rBQBB   7Md1QgQ:                            
--                                                                 YgBBQBQBQBQBBu::         K    UBBR   7UPQB.B:                            
--                                                           rYRQBQBQBMBQBBBi77.            M    PBBQ   . iBL77.                            
--                                                      .iMBBQQQBQBQBQBQQgi       i:.       BuJSBBBBB  ... .i .r                            
--                                                :bv:rZQBQBQBgBQBPBQE:         qBQBQB:.iUuU.7iSr7QqrrKBBBQKvJ5ggB                          
--                                      .:. .vZQBQBBBRBQBQqiBQBQr.      rIqY:  Sq.XBBQDPI:  .ui  .r PQBBBQBBBQBQQ:                          
--                               .::.rPJqdgdEBQBQBZBPgBBQBQBRP:      rYUQBBBQB:Q:.:jr.     .dU   P  :siIBBBBQBQLB.                          
--                      .     .KSIBQMQJBgsiUBBQDBMQdDQBQBQQs.       :q    IBBgKii:JL       ig   2v :U5: .QBgB2gEBB.                         
--                   rBBQgI7riULiQK7MZ7BQS7BMBZQRBQBQBQZ:    :LdQBBQR  :77ri..   :d        75   E  s7I   i jIB.BIBD                         
--            7:IJu5BQB7iUgXIiJrgLsRrvBddMBBBQBQBQBPY.      Qi  vQBQBiuuY:.      P5       .vI   Z  i71  g   uQiZvQB                         
--       . ..QZdSiIBEP1rr1Mq.1vYYdq.rD52dP5BQ5YSir         P.  :7dji.:.          d7        7s   Q  YIJ .B   iB:ELBQ                         
--      rrJK1s7uJj571IQE vBviQ:UMvB.UQBBB2d.         .::7r:R2YqYZ                U7        iY   Dr .1iDPBQi.2B BYQB                         
--    .B sq::7.Yi5 ..IBBvvQgdb5PDggBQDbLiX     ..IRIrPPMbPqP:  j.                Su ::irr1Y:U    B  i17vMBQBB.2BqBP                         
--    QdJgv.:.rr17 5i7Q2B:sIDr7E.Ysru7r:    .jRRP:.idZr.  U   :K          i..:vr1SB:17I7KuugQL   .QiQ1i:ii:rvqBuBQ                          
--    QSgQqi::77YQ.L:Ug:.QSMggEXrIUr..  .L2QQB7: iqj     2.   v:   .::vviqQUJJ5uIvd5:vXPbgXv5B:   .IKXRP7EQBBBIZQQrEX                       
--    .rirKZKJB:KgErrLQBEPj1dPQPJ.:    U:  L5   Lq.      P    Ld7S7JjSP2qPEXUvri7JsKEQBb.E.s::B.    :2QBBQBQYiMQBQBQi                       
--   vr.j1Ud.rQuu5EBJJ25DB7:          QY.irU.JQ q:     ::s:YvPYQPduSrr727vs1KPEBQBQBQi7v : vBr:BX   .u:LgBEREBQBBBQB                        
--    iijDU  .X1BrU2PIRUi       . ..:.BUQ.B :gBiS...7rYsR7Z7MBjrIIgZgdQRQQBggqBQBQBQ:  1   :BQE BQv     7qZvbMBBRXBZr:                      
--        .     .i        .UQBQBZQurrBQ K Qi YQjQKZDEDEUQBQgvviBQBBQ7BQBBBQBQBQPJL:. UBBM1srBBQB LBBPu:i:77UQBuBBi:Qd                       
--                     :PQBQ.IP      YB E Ki:iBiKSBBBRBddvX: 71Qu7B LQMdBDQQBr:     YrX.vbBQjQBBB::QBQBQBQBQi rBBQ2iBQ.                     
--                 :SQQQL5i. r   .:ii uii:.UsSQBQM:  :       .QB EQ QB     UBr      B : rBQu5BQBBBX..  .BBQB .QBQBQd:Bq                     
--             .vvBsb7irq.  BvrYJv7:7..D   Pj QQBr  .J7qEDBdr rQ.L. s   iZr BQ      P.7  1BuBQBBBQBQK7  BBBQ  BBBQBQBDSv..LYi               
--          :uJriJrr:Y iQ  .dr..    .v Dr. :2 .L.JPBBBQPLgQBBBiUr:.i:rQY:BQ BB       BQ:  LBLXqKSXvIK ..1Li::dQBQBBQ.iJMB: :B               
--      v5J7Bqrq7Q25SQ7 B.  Prv:irir:i IBBBvi:i  .BQBg.iQBBZBMBgBIBQBQP: gv BQ     .ruZXs..                iBQBBBQB2  rvJis.BLriii.         
-- r7qdUQBYXP2QB qvr::  Q:  UK. .. .i7 r:gQ17S. :7BBQ riILrs::   .rBBBY  gd QB     .DdZbvgDBQ. rKBBUMQZBgb1QQi.v2  ..j7K:iv7:vrriPBE        
-- Ri7Y2 RS .:   u:     Q:  j:. .   .  ir7BPiQ.XY1r:. i:   7s .:   UuUi  QB:7B.     7vqv 1BQBQBBqLXQi    7i       .ri   EL        BQ        
-- Qr7ur:7r:7i.7:gR7sXBQ1BEPg:v2.:ZL.:I  B: ruB..  :        ...7. :BBBQ .Q   B      vL  :BBBQBQB:  P     gg ZYE   :i 1Q7  SPE7vv.:QU        
--:MQSBEgQuKZ7BQBqIS77BQK7vQB vIRYgBBB51grE. .7 B i:v         :r.i:vS.i.:.:r:Qi     ri.  gBBBQBB:  7     .Kii.:  i qBKd Y iQrPBQ.           
--budQiibU7777.ir7iqIqYbQ7iJX2 vJqM.Q7 RXSI: 1Q 7 :.5         gr     :75117s: YBb7v1J:ii.B 7QBBBQBBBQBBB     : i . BB d1L :i .BP            
--PSvZ55BJBRQiMbsI.v57vv:r2Ssqd5rUDiQ77BBBQQYBBZBE:...  r...  L r        :..: 5EBgBQRBgi j  YQQQBQBQBBBvQQ2..sB5Q2K.:i.qBQDQB:              
-- .  .775sK7gQZP12PusE2.L.QvrsPKviiru7XLLrLX2LdZQBdv. :.. .            .:   :Qv.BQBBQ.SQg5BBBQZQQQRDB  BBi  L2Qid:K L.::uBBQBQY            
--          1Kr:7vLDZ7PI1XuRY 7ivgX7sBrviiSbr...:.BKI:ru. . 7   .i   .. i:. rDBQ YQi   QBBBZMQP BZi:BQ  BQ.  Q QdiR.b:7.B7.UBQBQs           
--                 r vM7rrSErJvuSbIBYKPr:rbiY1Js.g7Prs2Y. ..7rr2i.::i::.r7:.iBQBq... vQBgBQBgQQ DB.Pr  7QBJ7rgs Qb7B.M2ui:d  BgB:           
--                   :.irIP.1Quqi7v5:XDP5 BvB7iQDBiBUZvQjSX1..  17Y.:vBdL:r:::.irirsdQqSBQBBBgBQ.r:   iQBQi7Lri  . .           Pv..         
--                     : iB.su.D:: K.M Yq.UiQJ.rrr.D.5rrQKbBQY:1jIQSrLvY   iv1YQDQbii:... .. .:v7..JJBQBQQ SuKXRdXqdgBDQZQUdDg5BSuJSIXIUrvJ:
--                        .  i :iP5 Bur7E:jiUbr7gXdiiri7di.gPjQvg1:SIQBQEXBQsPPIIL.   :r2rvPP7vv5PqXSi:::.SZQQBQBQBBBQBQBQBQBQBq5BBBBQBBBs  
--                                : . .i:D r.7:QYiS.ibIvBiYdrBURii7siKBrjb2B.SBZPUPdsRBjBEvBQQQs..   ri7vKv7.::.:i::.::i:vv1:L1dQBBgL:iqZ57 
--                                        i  7 : .B2:1bLsrr:Pj Z:X5:v i5udQ:.gBr7JIgBQ.v7XJIiDXU. J1KSBBM1BQqBBMD:777v5i:i:.i:ir7rr.        
--                                                 ...i Yu  Pii1gv2u7ZP:QUBiPBMXZ.PBY5KggSiSiJiBQBXrSrqB5X.LRPur.:.77EMBQBQBBBZKi:r:        
--                                                          :.     i: u.vi:LJi.r:7.i: :IS:SrB:J..Bi IQ.d:5UrBBr7BQBgB7jr2vB:2:              
--                                                                                                    .  v   :. . .                          
----New series of simple scripts that just work..nothing fancy 
