----New series of simple scripts that just work..nothing fancy
--
--                                                ,7        ,;                  ;;.       .,,,:....., ; ;5.   ,.,7:               
--                                                 U        ;                  .                         77;. ;l,0;               
--                                                 ;9     ;7               .:,.      .,,,...,,.     :;;7s;715Ylb Y;               
--                                                  v1   ;s             .::.         ...       :;7vs7;:.       ;7.; .             
--                                                   5c  1            ,;:                  :77Y7;.              0sl70,            
--                                      ::      ,7:,.;7 ;7          ;7;                .;ll7:                   2U ;9S;.          
--                                      .;51l7777; .,.  7S        ;7;   .           ;7sv7                       7@;; c95..        
--                                               :cSc7   7S7    ;c;            . 7cc7;                          7S7FYCl@.;;       
--T:                                        ;;;:.:7:      ,CY. 7l.  .       .:::Y7.               M7            s5,.7Z57v,5.      
--S0;                                    ...;1Yv7;7   .,:;:;v:;C           ,, ,C.               ,;@:57           5;;2777.UU .     
--bF;                           :::,:;:;77;.,   ::;;77:..     sY..,..    ..,;;l,               ZYs@: @s          7sTZ5.;1@7Y;     
--sGPX7                      ;Ys7::::,       ,:;:.   .:       77.:,..   .;7TFC .,            .@@@9Xhh5Pc          F7 SC:C7OU ;7   
--7Yl5UU1:                ,7Y;.        .:,:..         ,;       Y: ;..  :ssSs7  .;:          .@@C@5CbOU07           1. 2E5ZF 7l:,  
--l91777FMS7.           ,;;.       .:;;:               ,;.      7, .. Y#5:,.    .7,     .,.sG@XXc.1218C7;           l Ul,5.7.. :  
-- .G@C777Sh0s;        ::       ,;;;,       . .         .;    ,,77   7@Y          7,     :1l lMPb2dG5907Y,         77 sZ 7:; .  , 
--   .G@G57.YGhDUY:   .       :7;.           .           ;7;;7;:.  . 1F, ,,,.,..   :.   ;1Y, 7G7U;;57l5;;7      ;l7:: 7M.7l7  , : 
--     .9@bS,;lTlZbb9ZF;,.  ,Y7                     :;777;;:         .;..         ..; ;cY;:;.ls 7X, :Yvc7T:   .l7:Y ;7:Z: Xl, : : 
--       ,@@Zc,7;.,7SDP8DP55Y   ,:              ,;77;;.      .       . ... ..:;;:7;7;:;;;;:;;75:FM7,7..7C;; ,:Z: b;  7;77.sC7 , , 
--         1h5U;vXG7: ;9U5@@@F; :@F.        ,;77;.        . .   ;Y11s777;;7;7;,   .:.::;Y;;;7.5lSsv7;. vT;CZUc. ;@  .;7,YvYhS7  . 
--          .b2d#779Y;O0vl   77  7@scT7;  ;77;.        . .   7l2c;.               ..;c;::.:;; ;97;7, 7YOZTY,S.  @c :;Yc;5U ;XYl:  
--            9hDE  7;:;77v;. .,  7l 7@O:..         .     ;7s7,               777;2C77;..7: ..hU     ;YT7: :F ,9#...Y7S.57F Y7 v; 
--             sMDs;Ycl: 7UG777Y5Os5.:@C2v   .           72;                .s;  ;@;.;75sFF7 Y@@,.;77l7,  YO,;PE  ;5;l,;;7UZlM;.7 
--              :5U@717O,:d577Y;;;7,,;@Y7@E   .   ,7F#C;XP.                .M;   @P  ;#C@7;Ob7UdS7;757:7X#D. ,; .cd75: ;.775Z7@7  
--            .   v@S  ,P.7Z; ,PP7:;.,72;5M:   .7ScYv,  .                  l;.   PD;::;;2FY Ov7@8 l@,,77..   .;T00S9l  v;:7SFvs;  
--          .    ;;l@v  ;P.5Z:;ssc.;:  ZM XS ,7;;                          7Y,, 7;5s;.  :Yh ScY75.0;5ZST   ;5GEXbPds ;;2c s.;G    
--            ,77;   S7  72.;;;: ;v@9:7EO,,@O,                             .b ; :T.  . ,Y7:l97;;Y1,l@UsM#X0#ZCU@@bX. ;sY; 7;;     
--         ,;7;.          ;9;.;:,O99M7Y7777Y@c  .    .                      7b7:     PM0Y;@@@@M@#27YMvl@@@M#@@@97,Z7  7.77 l      
--    .,:;;;.        ;0h77;9@7777l,SCYDM5:,;Uh: 7@7cYSST,                    .PP7   7MGl;Zd  1YS@@l71GMG8DcsY;YS  ;Z; ,7 G.l:     
-- .77;::              U@c;:;:.;;,;77s9DlcXsF@7  P,    ;@F;                    ;@8@@@MZ:O@S  7E@S;0PY7  7l7    55: :;,5; :1:v     
--ss:                 ;7:;7: ,,::sC2777;;CXPP8c ,1 : 5;:v@@.                    @@@@@@Z7YGb2vF@5  @@77;. .sS7:,:77.   C;  Z.T,    
--,                .7C7    .;OFU8O:,,,7. Od1FlXOb:Yc7@7   Y   ,7;.              vbFO9bYP8 2U@@9  U@7 ;57:  .;;;:;     X;  Y7;,,   
--         .     ;ll;        bhT777c7;,; :GX@hv;S;77:O@l     vZYvO5c77;;,        5;:U@Y@@7.@P@0;@8;  1@;;;::   .;     S;   X.7.   
--            ;;77.      ,T2v      ,;;v;7Ys;;h:;2UlFU:7b@MFS#7 .   .;:;70s.     .SYs7;0M;@@..,SXZY:,C@E  77:7:;;.     Y:   s77.,  
--       ...7v77:,;7;,,l;;;.             :7;:,;Y7Z; 797U#GE2 ,.         :5F7.    X,   Y@l07.Z5P;;:;7Z7  ;F;::,.       ;:    O;;.  
--  ,.:;7;;::...,:7,  ;,                 ,7  ,;:7T7:;7E9c;;;YU57svTCTTs7YlPbDT   @Y7SYMP@;;@; :h@S;   .;Y7;,,,        :;    2;7   
--cs;.                                    7 ;C;vc7;75SP17;::;;77,@@.       .:7 :8@F;70@@:s@#T7YF#D9M7;7;;;..           s    .F.7  
--                                        7.cd  :1P2X75Z;l27CS7O#@E           ,P7P5252;;M@DU@7Z@F5h9OFP. ,77.          v,    U,7  
--                                         ;Y@5   ;@YlcT15TcGDTX5O#Y:         @UY  ::;Y5MM@M;9h7 @9Ss7, ,;vC;:         :7    ;l;; 
--                                           1@:   ;.7@S;sG@7,.;GZF@@O;      @Y;7ch7  7;  717lX7YY;    :,7Y;.           C     Z:T 
--                                                ;,  7@ Tl;;T; ,7;Y#2:7   ,MS:s757ll7297     ;s1:; .;77;..;;:.         75    ;s; 
--                                               .E7   l; ,2O7Y;:;5;7Gl;: 7257; T9;:2277@@D7; G ; 7cS@s:;; ;7c;          v     Z,,
--                                                :d,   9s:Y8@#575;YGS@C9Tv:;7ldv,F5CE;cCE@@@hFv2ST90@.;.7 ;;;7          :7    Y7,
--                                                 ;O   O7    ;299D@@7@@;77YZGc:h#GX@#TS:7UP2PUYlZ@T.57:;.7 7;;7          7:.   Z 
--                                                  77  ,E;      :;1sMd7YP7lSSC58@X;T7Y97;;C82sY0X777Ts l.;;;C;;;          T.   T:
--                                                   7;  l5.       ;2:;Y7;S7;2@@; .:l75b7,G@1YX:7C8Sd@@,,l ;71Fs7;.        ;l.   l
--                                                    ;7,.s7         s;;.,7:UEvSY  P@1M2 S@@0d57U5s1vvCU7:Y7,;7T;;;,        Y7.  c
--                                                      ,:5O.         . lF;Xc;  ;SEEF8S,sDMY77vOFC7;71Y70S .Y;,;YYc7:        l;.  
--                                                         F;            ..Y;Tc:  7S2Y;Td07;XXEY. ;E7C75,Yh; ;v;.,:Y7,        s:. 
--                                                                            .7Y.s7775vM0;159@@:.M@97ssllX01;   ,,,777.      .T7 
--                                                                              .0;;7;O1YS##S2hM7;D5TlUMO77Y5Cl7:,,,.,.;.       7;
--                                                                              1....72Z, 775Y7;TC2YSX: 7FS;:;YlCs77;.:Y5T       :
--                                                                             :s  :YS5:  77. .7EUZ, YC.;7lClY;;:;:;;,C5Y7        
--                                                                              l: ,7;  .;7  7;7; :;;:2D. ,:. ,;7::,. 77          
--                                                                              v..;.  .,.  ;;;7 :     YU       ....7; 7:         
--                                                                              E,    ,.: .;:;Y .:7;    s7      . . .;:;l7:       
--                                                                             ;7    ...,;,,;v;:;  :;:   Yv       .;77;:;7;       
--                                                                             c;       . ,,;7; .::  .7;  ;5;   :cc;;    ,,;7;:   
--                                                                            ,,.,:77.   ::7Y.     :,  ,;;  7Y.vGC:.     ;;,;;;   
--                                                                           ;    ;7;;7:, lO.        ,,  .,. .2;7Y:;7777;7;: :7,  
--                                                                           ;:;;;.;;.1c;FF:           ,,   ;,; .7;1U: . .;; :7;: 
--                                                                          ,;  .77;:;l;YXY              .,  .77, :;;ls777;.;;,;  
--                                                                           ;,;;,,7;;,,;v7.               .:. .;,,: ,,,:s: ,. ;: 
--                                                                           ;v,,:;::    c::                 .,   ,;77;,,; ..  .; 
--                                                                           77,,:,,    .l.,                    .  ,:,:::..:    : 
--                                                                           :          ;:                                        
--
--
--                                                                                                     .Y..                                 
--                                                                                 .:vXgdBBQKgs.     XQq.i:vJ                               
--                                                                          ..KRBBBBBBBBBEX1BBBD1.:1BBP:7:7YQ2X.                            
--                                                                    iY7BBBQBQBBBBBdr     5QL..rBQBB   7Md1QgQ:                            
--                                                                 YgBBQBQBQBQBBu::         K    UBBR   7UPQB.B:                            
--                                                           rYRQBQBQBMBQBBBi77.            M    PBBQ   . iBL77.                            
--                                                      .iMBBQQQBQBQBQBQQgi       i:.       BuJSBBBBB  ... .i .r                            
--                                                :bv:rZQBQBQBgBQBPBQE:         qBQBQB:.iUuU.7iSr7QqrrKBBBQKvJ5ggB                          
--                                      .:. .vZQBQBBBRBQBQqiBQBQr.      rIqY:  Sq.XBBQDPI:  .ui  .r PQBBBQBBBQBQQ:                          
--                               .::.rPJqdgdEBQBQBZBPgBBQBQBRP:      rYUQBBBQB:Q:.:jr.     .dU   P  :siIBBBBQBQLB.                          
--                      .     .KSIBQMQJBgsiUBBQDBMQdDQBQBQQs.       :q    IBBgKii:JL       ig   2v :U5: .QBgB2gEBB.                         
--                   rBBQgI7riULiQK7MZ7BQS7BMBZQRBQBQBQZ:    :LdQBBQR  :77ri..   :d        75   E  s7I   i jIB.BIBD                         
--            7:IJu5BQB7iUgXIiJrgLsRrvBddMBBBQBQBQBPY.      Qi  vQBQBiuuY:.      P5       .vI   Z  i71  g   uQiZvQB                         
--       . ..QZdSiIBEP1rr1Mq.1vYYdq.rD52dP5BQ5YSir         P.  :7dji.:.          d7        7s   Q  YIJ .B   iB:ELBQ                         
--      rrJK1s7uJj571IQE vBviQ:UMvB.UQBBB2d.         .::7r:R2YqYZ                U7        iY   Dr .1iDPBQi.2B BYQB                         
--    .B sq::7.Yi5 ..IBBvvQgdb5PDggBQDbLiX     ..IRIrPPMbPqP:  j.                Su ::irr1Y:U    B  i17vMBQBB.2BqBP                         
--    QdJgv.:.rr17 5i7Q2B:sIDr7E.Ysru7r:    .jRRP:.idZr.  U   :K          i..:vr1SB:17I7KuugQL   .QiQ1i:ii:rvqBuBQ                          
--    QSgQqi::77YQ.L:Ug:.QSMggEXrIUr..  .L2QQB7: iqj     2.   v:   .::vviqQUJJ5uIvd5:vXPbgXv5B:   .IKXRP7EQBBBIZQQrEX                       
--    .rirKZKJB:KgErrLQBEPj1dPQPJ.:    U:  L5   Lq.      P    Ld7S7JjSP2qPEXUvri7JsKEQBb.E.s::B.    :2QBBQBQYiMQBQBQi                       
--   vr.j1Ud.rQuu5EBJJ25DB7:          QY.irU.JQ q:     ::s:YvPYQPduSrr727vs1KPEBQBQBQi7v : vBr:BX   .u:LgBEREBQBBBQB                        
--    iijDU  .X1BrU2PIRUi       . ..:.BUQ.B :gBiS...7rYsR7Z7MBjrIIgZgdQRQQBggqBQBQBQ:  1   :BQE BQv     7qZvbMBBRXBZr:                      
--        .     .i        .UQBQBZQurrBQ K Qi YQjQKZDEDEUQBQgvviBQBBQ7BQBBBQBQBQPJL:. UBBM1srBBQB LBBPu:i:77UQBuBBi:Qd                       
--                     :PQBQ.IP      YB E Ki:iBiKSBBBRBddvX: 71Qu7B LQMdBDQQBr:     YrX.vbBQjQBBB::QBQBQBQBQi rBBQ2iBQ.                     
--                 :SQQQL5i. r   .:ii uii:.UsSQBQM:  :       .QB EQ QB     UBr      B : rBQu5BQBBBX..  .BBQB .QBQBQd:Bq                     
--             .vvBsb7irq.  BvrYJv7:7..D   Pj QQBr  .J7qEDBdr rQ.L. s   iZr BQ      P.7  1BuBQBBBQBQK7  BBBQ  BBBQBQBDSv..LYi               
--          :uJriJrr:Y iQ  .dr..    .v Dr. :2 .L.JPBBBQPLgQBBBiUr:.i:rQY:BQ BB       BQ:  LBLXqKSXvIK ..1Li::dQBQBBQ.iJMB: :B               
--      v5J7Bqrq7Q25SQ7 B.  Prv:irir:i IBBBvi:i  .BQBg.iQBBZBMBgBIBQBQP: gv BQ     .ruZXs..                iBQBBBQB2  rvJis.BLriii.         
-- r7qdUQBYXP2QB qvr::  Q:  UK. .. .i7 r:gQ17S. :7BBQ riILrs::   .rBBBY  gd QB     .DdZbvgDBQ. rKBBUMQZBgb1QQi.v2  ..j7K:iv7:vrriPBE        
-- Ri7Y2 RS .:   u:     Q:  j:. .   .  ir7BPiQ.XY1r:. i:   7s .:   UuUi  QB:7B.     7vqv 1BQBQBBqLXQi    7i       .ri   EL        BQ        
-- Qr7ur:7r:7i.7:gR7sXBQ1BEPg:v2.:ZL.:I  B: ruB..  :        ...7. :BBBQ .Q   B      vL  :BBBQBQB:  P     gg ZYE   :i 1Q7  SPE7vv.:QU        
--:MQSBEgQuKZ7BQBqIS77BQK7vQB vIRYgBBB51grE. .7 B i:v         :r.i:vS.i.:.:r:Qi     ri.  gBBBQBB:  7     .Kii.:  i qBKd Y iQrPBQ.           
--budQiibU7777.ir7iqIqYbQ7iJX2 vJqM.Q7 RXSI: 1Q 7 :.5         gr     :75117s: YBb7v1J:ii.B 7QBBBQBBBQBBB     : i . BB d1L :i .BP            
--PSvZ55BJBRQiMbsI.v57vv:r2Ssqd5rUDiQ77BBBQQYBBZBE:...  r...  L r        :..: 5EBgBQRBgi j  YQQQBQBQBBBvQQ2..sB5Q2K.:i.qBQDQB:              
-- .  .775sK7gQZP12PusE2.L.QvrsPKviiru7XLLrLX2LdZQBdv. :.. .            .:   :Qv.BQBBQ.SQg5BBBQZQQQRDB  BBi  L2Qid:K L.::uBBQBQY            
--          1Kr:7vLDZ7PI1XuRY 7ivgX7sBrviiSbr...:.BKI:ru. . 7   .i   .. i:. rDBQ YQi   QBBBZMQP BZi:BQ  BQ.  Q QdiR.b:7.B7.UBQBQs           
--                 r vM7rrSErJvuSbIBYKPr:rbiY1Js.g7Prs2Y. ..7rr2i.::i::.r7:.iBQBq... vQBgBQBgQQ DB.Pr  7QBJ7rgs Qb7B.M2ui:d  BgB:           
--                   :.irIP.1Quqi7v5:XDP5 BvB7iQDBiBUZvQjSX1..  17Y.:vBdL:r:::.irirsdQqSBQBBBgBQ.r:   iQBQi7Lri  . .           Pv..         
--                     : iB.su.D:: K.M Yq.UiQJ.rrr.D.5rrQKbBQY:1jIQSrLvY   iv1YQDQbii:... .. .:v7..JJBQBQQ SuKXRdXqdgBDQZQUdDg5BSuJSIXIUrvJ:
--                        .  i :iP5 Bur7E:jiUbr7gXdiiri7di.gPjQvg1:SIQBQEXBQsPPIIL.   :r2rvPP7vv5PqXSi:::.SZQQBQBQBBBQBQBQBQBQBq5BBBBQBBBs  
--                                : . .i:D r.7:QYiS.ibIvBiYdrBURii7siKBrjb2B.SBZPUPdsRBjBEvBQQQs..   ri7vKv7.::.:i::.::i:vv1:L1dQBBgL:iqZ57 
--                                        i  7 : .B2:1bLsrr:Pj Z:X5:v i5udQ:.gBr7JIgBQ.v7XJIiDXU. J1KSBBM1BQqBBMD:777v5i:i:.i:ir7rr.        
--                                                 ...i Yu  Pii1gv2u7ZP:QUBiPBMXZ.PBY5KggSiSiJiBQBXrSrqB5X.LRPur.:.77EMBQBQBBBZKi:r:        
--                                                          :.     i: u.vi:LJi.r:7.i: :IS:SrB:J..Bi IQ.d:5UrBBr7BQBgB7jr2vB:2:              
--                                                                                                    .  v   :. . .                          
----New series of simple scripts that just work..nothing fancy 
                                      


if myHero.charName ~= "JarvanIV" then return end
