--                                                                                                                                                                                                                                                                                                         
--                                                                                                                                                      
--                                                 :;.         .                                               ,,                                       
--                                               ;i;          .     ..::,,;;;::.,                              ,2r                                      
--                                              Fr   .    ;r      .,;;::..   .   ...        ;:                   ;2,                                    
--                                            .br       .r.r    .,rr;,......;,,,,. .:       irr                   :P;                                   
--                                            C;         i ;:  ,rL:             .:;:..     r; c                    :;;;                                 
--                                           cr   . .r   5, r:rjc.                 :rr: . .7 ::   r                ,; ;r,                               
--                                          ;C     ;:r5  r, :Lr,                ;:   :ir:.;  t   j;r:              .r   r;                              
--                                          n      ;  Z .;.r7.                 ;;..    .rc. r;  jr ;i               ,    ,r.                            
--                                         Fr      r, ;i;;r,                  ,r  ;.     ;r:;; ir  5                      .c:                           
--                                        .X       ,i  ;;:            ,, .   .c   :;       :r;i;  i;                        L;                          
--                                        j,       .; ;r           ..,,.;;  ,i     :   ;r   .r,  :r                          C.                         
--                                       X@       ;:,r,           , :;: :  ,r.     ; : ,r.,   ;; c,                           T                         
--                                      F@;      r;;;    ;  ,.  ,; ,;. ,..;r      .,;s ;,  ;.  ,iri.                 . ,      ;r                        
--                                    .tXL     .rr;:    ;U:;; .,, ;:  ,;cr,       .r:; ;,   r    7;r;                  :,      r;                       
--                                   :c..     ,;;, r  .r5L ; ..  ;. .r;r;         i;,..r    ,;    rcr;                  ;       r                       
--                                  :t      ::;r  .;  i;d  :,:  .,;r;.           Lr ;:;      ,c r  ;;,r                 :r      :j  .                   
--                                  F,     ;;7r  ;r  r.L. :::  :;;,             r;  i;. . .:.iT;;;  ;r.r:                j:      t;                     
--                                 ;c     ;;rr. :;; r;ir ;T                    :.  ;i...;,:..5;;;r,  .r,;;                U       O                     
--                                 n    .;;U,; ; ..;;.:.:F;.                      ;n,:,,,,...:  r;.r   r;,i,              ST      rr                    
--                                rT   ;;r;;c;;  ;;.    ;, :;:.                  .Cr:..         s. r:   rr.5;             .Z      .U                    
--                                F  .rrc..rx;  rr           .:r;               ;r.    ..;;; .  ;.  ; .  .;,;;             g:      r:                   
--                               rs :;,i;  Cx :r;      ...,,.   :r7   ;  ;    :r;  .;;rxcc7rs;;.    .,r;   C;.L            rx       r                   
--                               O ;j;: ;, sx:i.   ,rr;:rc::::;;  ;j;r:  ;r,;;. .rrr;.;.    ,; ;U:   ;jr  .r,;.r           .s       j:                  
--                              ;r;L;:  .c .L   :r:.    i      2::;.;.    ;i, ;;:.    r      ;;T:    ;i;  i. r; r,          r       rT                  
--                              CiLr:    t  s   .cCr;    ;    ,n;;tr..    .. Cx;,:;;:.,rrr,cU2L.     ;;;  : , 7i i          T.      .i                  
--                             rO;i;     i  s     .;HFirrEgsT7Lr;.  ,       : .;;;rrrr;iCrrSc          ; ;  ; ,7T r        .P        i                  
--                             Lrrr      s. c        : :ir          .;     ..           : r           .,r; ;  ; Cr ;       ;H  .::,: s.                 
--                            ,xrr       ;r r        : .:                                .;           ::S, ; .;  g..;      r;.r;:..:rT                  
--                            cL,;        :TT        ;.;         .,;;;rr;r,:..           :;.         .i.;  ,;r:  ;H r.     d;:      :L                  
--                            iX ;         ,c        ;;,      ,;r;;;;;,.:.:;;:;;,       ,,;.        .r. r ;;7S   rc 5     xg                            
--                             #:L          r.       ;;.    ,irr;;,. .   ...,;;;;;;.    ::,            r;.;.F;   X x;    ,P        .                    
--                             r:s;         x; .     :.,.,;cr:,,.             ..,;r;;:. ;.;           ,r ;:.r   O rc    .O.                             
--                              s i         ;c,;;;;;.c;r7r;;,.                    .,;;:r:7,       ..;;.r.c     S;;n     8;                              
--                              :r r         ;..;:r;:,;,:..                         .,;;;;;:;;;::;r;:.Tjr.    rr;;    .O;                               
--                               ;i.r.       .; r ,:                                     ...:r:.r:,: ,:Ts    rirr    r6.                                
--                                ;r:;:       r::. r                                         r  ;    r r.   ;ir;    LF:;                                
--                                  ;;;r       j ; ;                                        ;, ;.   r,     i7r,  ..F6, ,r  .                            
--                                   ,;;s;     .;;,.:                                   .  .r ,;   ;r     s;r  ;7;,.    ;:                              
--                                     ;:rs.    ;r;.;                                     .; ;;   .T     r,;:;r;         i                              
--                                      rr:rr    ;;;T;                                   .r ;r    r    ;; 7rr:          .r                              
--                             .    .;rc;.;r;;    ;  .                                  ;L;;,    i,   r..Pc:            .s     .                        
--                                .Tt;:    ;Lrr:   ;                                    ..      ri  ;; U@;               x;:;.                          
--                               ,c;  .;     r7rr  .r                                          ;;; s,:BD                 r; ,;;                         
--                              .L.    :r.    .;7r.  ;                                        r:.j; ;D;                  .2;. :i                        
--                             .T.      .;;     .rs; .d                                      ;r;: .r;                   ;Li.   ;c                       
--                           :rrr         ;r;     ;si.C;.                                   Zj:.:ti                  .ri;       r;                      
--                          7j;r            ,;;.   .7nr ;.                                :tr:;7;.               .;ci;.          ;;.                    
--                        .r; ,r  .           ,;;.   ;r: ;:                             ;ri;;;.               .;rrr,          .   .r:                   
--                   .   ,L.   ,;               .rT;  ,L: ,r                        .76nc;,.               :rcr;.                   r.                  
--                       s.     .rr               ,;si,;6; .i.               .,,;;;;;r:           .     :;rr;                       rC                  
--                     :B;       .cS;                .;,rbj. ;;.     ..,:::r;:,:..                 .:rrr;,                          5Cr                 
--                    ;Sx;          rr7:                  rrr;SZrrr;:::.. .                   .:;;;;;,                      .      T: rT.               
--                .,,.X  U:           :cTr,                                              .,;rr;;.                                 rr   .;;              
--           .;;,.... c   s;             :;rr:,                                     .,::;;:,.                                   ;i;      .r             
--            .;rs;   c.   ;;                :rr;;.,.                      ..::;;rrr;,.                                      .;r;         x             
--           ..,;r.   .i    ,;.                 ..,,:;r;;;;;;:;,,,,,;:;;;r7;::;,.                                         ,:rr;          Ui:,           
--        .:r::r.      :i    .;r                         ..;;;;;;;;;....                                              .;rc;,           :i;  ;:          
--      ;r:   ;,:r,     .;;    :r;    .                                                                     .      .;;;:.             ss     ,;   .     
--    rr.      .:         rC:    rc;   .                                                                      .;;;:,.              :;i:        :.       
--  ;r;   .  ,;;           .xF:   .;;,                                                                  .:;;;;;:.               ,;ir,        .;.;:      
-- ;c.      ,; :;            :Tr     ,:,.            ,:,,, .                                      .,:;;;;;,.               .,;;7r;     .;;,;,.s7;r      
--r:           ;.         .     ,;.     ,::.            ..,,,,,,:.. . .                     ..;;r;:,.                 .rTijr;,.        ;; . ... :;r     
--.  .       .,.                  ,;:     .;,.                 ..,,,,:;;;r;;::::,:,:,:::,:::,:..                   ,:rcr,              .;        Cc     
--         .;;;                     :;;.                                      . .........           .,.         ,;rr;           .:,,,;; ;,       :t     
--           ::                       :r;.                                                     ..:;;:,.      :;;;,               r       .        r:    
--          ,,                          :rr.                                                ,,;r:.        ,;r;.             ,.r:.;;               ;5    
--         :                               ;,                                             :;.            ,.                 , .                    n    
--
--   r2X99H9H9HGGi  sX99H9H9H993;                        ,,                                          ,:                                                 
-- ,B@B@B@B@B@@@B@B@B@@@B@B@B@B@B@,                     B@Br                                        ;@B@                                                
-- B@Bs          B@@B          s@B@                     @B@r                                        ;B@@                                                
-- @B@           s@@5           B@B                     B@Br                                        ;@B@                                                
-- B@B,          3@BA          ,@B@   ,GGAAAAAA2A23;    @@@;     :9XXAXAA22sss32r  s9AAAA2A2AA2i,   ;@@Bi2XAXAA2s;    s9XAA2AAAAA2s,      i3AAAAX22r    
-- @B@,          2B@2          :B@B   ;@B@B@B@B@@@B@B;  B@Br     sB@B@@@B@B@B@B@B  @B@B@@@B@B@B@B#  :@B@B@B@B@B@@@B   B@B@B@B@B@B@B@B   2@B@B@B@B@B@@A  
-- B@B:          2@BA          ,@@@                B@B  @B@r              iB@BB:               H@Br ;B@B        3B@B              9B@i ,@@@        B@B: 
-- @B@,          2B@2          :B@B     r9@@B@B@B@h@B@  B@Br            s@B@#,      ,S#@B@B@@@h@B@s :@B@        ,@B@   ,5#B@B@@@B#B@B5 :B@B        ;25  
-- @@B,          2@BA          :@B@    @@B@H##B##H9B@B  @@@;          2B@@#        2@B@#####BHGB@Bi :B@@        ;B@B  SB@BBH##B##ABB@s ,@B@             
-- @@@,          2B@2          :B@B   A@B9         @B@  B@@;        2@B@3          @@@         5B@s :@B@        ;@BB  B@B         i@B3 ,B@B             
-- B@B;          9@@h          ;@B@   ;B@B3isissii@B@H  sB@@2sS5  hB@B@2::rriiss;  B@B@iiisssi2B@B, ;B@B        rB@B  B@@Biisssii3@B@, ;@B@             
-- hB@           sB@s          ,B@B    ,H@B@B@B@B@B@s    ;B@B@B@ rB@@@B@B@B@B@B@B   s@B@B@B@@@@@H,  ,@BH        :@BG   sB@@@B@B@B@Bh,  ,B@H             
--



require 'Eternal Prediction'

